### ISSUE TITLE
Data being displayed is behind by 2 days

### ISSUE THREAD

**Issue by toddocon** [Autodesk/hubble#118]
Today's date is Feb 7 however the data being displayed in Hubble is only up to Feb 5. I looked at the raw data files and they indeed have data for Feb 6.

I collect data every morning and always have seen Hubble display day -1 (which is expected). Now, though, Hubble is displaying day -2 but I keep collecting the data at the same time every morning. 

Thanks for any insight.

**Comment by larsxschneider** [comment]
As discussed via email, I think you are right that Hubble 0.2 doesn't work on GHE 2.10.x because of a database schema changes. I'll look into a workaround tomorrow. Right now your best option is to revert the update to Hubble 0.2. Sorry!
