### ISSUE TITLE
Git traffic and tokenless authentication charts empty after GHE upgrade

### ISSUE THREAD

**Issue by talktopiyush** [Autodesk/hubble#139]
Hello there,

We have hubble as service on a dedicated machine and we recently did GHE upgrade from v2.11 to v2.12.6 and after this hubble does not show the git traffic/ there is no data in git-download.tsv

fyi, there are no errors reported when we run `update-stats.py`.

In general do we need to do anything before or after we apply an update to GHE.

Regards
Piyush

**Comment by talktopiyush** [comment]
similarly no data (or marked as zero against date) in tokenless-authentication.tsv since the upgrade.

**Comment by pluehne** [comment]
Hi @talktopiyush! Thanks for reaching out about these two issues. We noticed the issues with the *Git traffic* charts as well, and they should be fixed by #138.

I’d like you to check out the latest commit in the `master` branch and to run the Hubble updater again. This should resolve the first part of the issue. (The context is that we made changes to the naming of the data series, and unfortunately, these weren’t reflected in the data files that the updater produces. Hence, the dashboard couldn’t find the data anymore and would show empty charts.)

Concerning the *tokenless authentication* chart, there was a change in GitHub’s log file format from 2.11 to 2.12 that broke our script for that chart’s data. I’m currently working on this and hope to have a patch out later today.

As a general suggestion, we recommend that you use the latest release (currently, 0.2.0) and not the `master` branch directly. Also, we’re trying to avoid issues on `master` as best as we could, but we can’t guarantee forward compatibility with new GitHub Enterprise versions unfortunately.

**Comment by pluehne** [comment]
@talktopiyush: In the meantime, please let me know whether #138 fixed the issues you experienced with the *Git traffic* charts.

**Comment by pluehne** [comment]
@talktopiyush: I forgot to notify you, but we merged my fix #141 that should resolve your issue with the *tokenless authentication* chart. It would be great if you could test all these changes and tell me whether we can close this issue :smiley:.

**Comment by rajivmucheli** [comment]
Hi @pluehne post upgrading, i can confirm Git Traffic Chart is populating data but tokenless-authentication-detailed.tsv FAILS,  please note tokenless authentication.tsv gets updated.

**Comment by pluehne** [comment]
@rajivmucheli: Happy to hear that the *Git traffic* chart is fixed for you now. Can you explain what exactly fails with the detailed *tokenless authentications* report? Is it just empty or do you get an error message?

Also note that the *tokenless authentications* chart has recently received a fix in #141. Did you experience the issue before or after this pull request had been merged?

**Comment by rajivmucheli** [comment]
The report doesn’t process i.e wouldn’t update like other reports. Hubble-data repo for this repo shows last updated was 16th March, which was we updated GHE to 2.12.

I guess after the pull request? I see this fox was on 16th March as well!

**Comment by pluehne** [comment]
@rajivmucheli: Do you get any errors in the log? GitHub Enterprise 2.12 is meant to be supported by Hubble, so this shouldn’t be a problem. Also, could you try manually executing the [https://github.com/Autodesk/hubble/blob/master/updater/scripts/tokenless-auth.sh](`tokenless-auth.sh`) on your GitHub Enterprise appliance? It would be interesting to know whether this script produces output and, if not, errors.

**Comment by pluehne** [comment]
@talktopiyush: It would be interesting for me to know whether you’re facing the same issues as @rajivmucheli :slightly_smiling_face:.

If everything is resolved for you, I’d like to close this very issue and to open a new one for the problems with the detailed *tokenless authentications* chart that @rajivmucheli is facing.

**Comment by talktopiyush** [comment]
@pluehne we are in the same work group :)

**Comment by pluehne** [comment]
@talktopiyush: That’s what I suspected, but I wanted to make sure that these aren’t two unrelated issues :smile:. If you have the time, it would help if you could try what I suggested above a few minutes ago :slightly_smiling_face:.

**Comment by talktopiyush** [comment]
@pluehne  We have updated hubble to the latest commit. hopefully tomorrow this will get populated. keep you posted. myself or @rajivmucheli will keep you posted. thanks for the help

**Comment by pluehne** [comment]
@talktopiyush, @rajivmucheli: All right, and thanks for helping us debug the issue :slightly_smiling_face:!

**Comment by rajivmucheli** [comment]
@pluehne 

I am not sure if the latest updated fixed the issue, i initially executed update-stats.py manually but had no luck. As suggested by you, (i gave chmod +x tokenless-auth.sh) to the script, o/p is:

[scripts]# ./tokenless-auth.sh 
user    repository      tokenless authentications
cat: /etc/github/enterprise-release: No such file or directory
gzip: /var/log/github/gitauth.log.1*.gz: No such file or directory

Prior to the upgrade it worked well, hence would creating the above directories help?

**Comment by pluehne** [comment]
@rajivmucheli: Just to be sure, did you execute `tokenless-auth.sh` on the GitHub Enterprise appliance? It won’t work on your local machine :slightly_smiling_face:.

**Comment by rajivmucheli** [comment]
@pluehne hope there wont be any impact? to confirm i copy the script & execute?

**Comment by pluehne** [comment]
I generally recommend you review whatevery you intend to execute on a GitHub Enterprise appliance. As you will see, [`tokenless-auth.sh`](https://github.com/Autodesk/hubble/blob/master/updater/scripts/tokenless-auth.sh) only performs a few file processing commands.

From my experience, the script doesn’t take long to complete (less than a minute, I would expect), and it is executed with each call of `update-stats.py` anyway. That’s why I would say that it is safe to copy and execute on your GitHub Enterprise instance :slightly_smiling_face:.

**Comment by rajivmucheli** [comment]
the scrip executes successfully, gives me tons of user info (like it initially worked):

./token.sh
user    repository      tokenless authentications
**confidential info

**Comment by pluehne** [comment]
@rajivmucheli: Good, that means that the script itself is working as expected. Hence, I would think that the tokenless authentications are correctly collected by Hubble’s updater.

Out of curiosity, can you confirm that the (confidential) output you got is indeed different from the `tokenless-authentication-detailed.tsv` that’s in your `hubble-data` repository?

Also, can you once again look at whether `update-stats.py` produces any warning or error message concerning the *tokenless authentications* report? For your convenience, you may temporarily comment out [all the reports in `update-stats.py`](https://github.com/Autodesk/hubble/blob/master/updater/update-stats.py#L75-L98) except the [`ReportTokenlessAuth` line](https://github.com/Autodesk/hubble/blob/master/updater/update-stats.py#L97), just for testing. In this way, only this single report will be updated, saving you some time.

**Comment by pluehne** [comment]
@rajivmucheli: Happy to hear that you got updated data now. However, I don’t see a reason why it didn’t work before but it does now.

Let’s give it a few days. Could you tell me by the end of the week whether you got updates with the detailed *tokenless authentications* report every day without trouble?

**Comment by pluehne** [comment]
@rajivmucheli, @talktopiyush: Is everything still working fine on your end? I’d just like to know whether we can close this issue :slightly_smiling_face:.

**Comment by talktopiyush** [comment]
Yes it works again.

thanks

**Comment by pluehne** [comment]
@talktopiyush: Thanks for the update!

**Comment by talktopiyush** [comment]
@pluehne maybe you could confirm this, graph are updated only once in a day regardless of how many times we execute the python script?

**Comment by pluehne** [comment]
@talktopiyush: Yes. If Hubble detects that there already is data from today for a given chart, it will not update the chart again. That’s to avoid recording duplicate values in the data files.

**Comment by talktopiyush** [comment]
@rajivmucheli this confirms why we did not have any data in the graphs even after update to the latest release on that day but it populated the next day.

**Comment by talktopiyush** [comment]
@pluehne thanks again

**Comment by pluehne** [comment]
@talktopiyush: Yep, I should have thought about this. In these cases, it’s necessary to remove the most recent Hubble commit, at least for testing :slightly_smiling_face:.

I’m happy to help. Feel free to stay in touch with us should you have suggestions or other comments.
