### ISSUE TITLE
Installation Documentation is lacking information on the meta.tsv file inside the hubble-data repo

### ISSUE THREAD

**Issue by IngoS11** [Autodesk/hubble#145]
I installed Hubble on a test machine and noticed that the README.md does not say anything about the need for meta.tsv to be present in the hubble-data repository. With an empty hubble-data repo the function `checkSchemaVersion` will fail.

**Comment by pluehne** [comment]
Hi @IngoS11, and thank you for telling us about your issue when using Hubble with an empty `hubble-data` repository.

I had tested the schema check with empty repositories, but what you report really sounds like a bug in the implementation. I’m not in office right now, but I’ll try to debug this very soon.

Can you tell me whether you’re using Hubble Enterprise 0.2.0 or the current `master` branch?

**Comment by IngoS11** [comment]
Hi @pluehne. I am using the current `master` branch. I did a fix and created a pull request, have a look if you like it.

p.s. I also found that there is a missing import statement for the `calendar` also described in #136
