### ISSUE TITLE
Date mismatch—timezone issue?

### ISSUE THREAD

**Issue by toddocon** [Autodesk/hubble#147]
Hubble data is collected from the prior day's rotated logs. That data is collecting properly on my system and being pushed to GHE. 

When I view the Hubble graphs, though, the date that is shown is day -2 but the actual data is from day -1 (which is expected). I reside in the Mountain Time Zone. If I Remote Desktop into a system in Pacific Time Zone the date that is shown is day -1 (which is expected) and the data is still OK. 

So for me, I'm seeing a display date issue but the underlying data is OK. 

I am using the latest released version of Hubble (0.2.0?) and GHE 2.10.6. There was no date display issue until I updated to Hubble 0.2.0 so maybe something was introduced in the new release. 

Our 2.12.X upgrade is a few weeks out. I need to install this Hubble on stage to see if the problem is still there.

**Comment by pluehne** [comment]
Hi @toddocon! I recently did some changes to the timezone handling (#143), so it could well be related to that. When you said that you use the latest version of Hubble, did you mean the `v0.2.0` release or a more recent version from `master`?

**Comment by toddocon** [comment]
Hi Patrick

I am using the latest released Hubble, v0.2.0. We are upgrading to 2.12.8 in a few weeks if that matters.

**Comment by pluehne** [comment]
@toddocon: Can you reproduce this issue on [autodesk.github.io/hubble](https://autodesk.github.io/hubble/)? That page is running an updated version of the dashboard with my changes in #143.

**Comment by pluehne** [comment]
@toddocon: It’s not urgent, but could you test whether the date mismatch issue is still present when updating to the newest `master`? I’d like to know whether there is still some bug to be chased :slightly_smiling_face:.

**Comment by toddocon** [comment]
@pluehne We upgraded to GHE 2.12.9 on Friday and I updated to the latest Hubble master as well. I am happy to report that today (4.16), hovering over a data bubble shows the date as 4.15. So the fix worked! All is well now. 

Thanks and regards.

**Comment by pluehne** [comment]
@toddocon: That’s great to hear! That means that we can close this one and #118?

**Comment by toddocon** [comment]
@pluehne : Yes, we can close both issues. Thanks for the help!
