### ISSUE TITLE
git-versions.tsv produces data file with lots of entries containing day and 1

### ISSUE THREAD

**Issue by IngoS11** [Autodesk/hubble#160]
Hi guys,
using v0.3.0 at the moment and for some reason on our GitHub Enterprise [ReportGitVersion.py](https://github.com/Autodesk/hubble/blob/master/updater/reports/ReportGitVersions.py) produces a data file with lots of entries containing the day and a 1. I ran the [zgrep statement](https://github.com/Autodesk/hubble/blob/master/updater/scripts/git-versions.sh) on a haproxy.* file for testing and get the same output with the day and 1. Output in git-versions.tsv and git-versionsnew.tsv looks something like this. 
`31      1
31      1
31      1
31      1
31      1
31      1
31      1
31      1
31      1
31      1
31      1
31      1
31      1
31      1
31      1
31      1
31      1
31      1
...
...
...
2.17.1  131
2.17.0  120
2.17    1
2.16.3  181
2.16.2  180
2.16.1  144
2.16.0  8
2.15.2  2
2.15.1  426
2.15.0  141
`
Has anybody else this issue as well? If I get some time tomorrow I will take the zgrep command apart and see where and why it happens but I am not the best bash/perl guy. My mileage may not be too good :)

**Comment by IngoS11** [comment]
I already found the problem but I am lost trying to make this work in Perl :). We have a special version here  `git/abapGit-v1.66.0-sap-1` and the version does not get extracted properly. Any Ideas how to remedy that?

**Comment by larsxschneider** [comment]
Thanks for the report 👍! Can you change the perl line to this and give it a test:
```
perl -lape 's/.* (.*):.* \[.*\|\|git\/([^}]*).*/$1 $2/'
```

@pluehne 👆 this would parse the full Git version. On Windows this could be `2.16.1.windows.1`. I think that's OK as we can sanitize the version in the JS layer, no?

**Comment by IngoS11** [comment]
it does work but I am not sure if this is ok for you guys. Output looks like this. 

      4 abapGit-v1.68.0-sap-1
      9 abapGit-v1.66.0-sap-1
      1 abapGit-v1.50.2
     95 2.17.1.windows.2
     37 2.17.1
     45 2.17.0.windows.1
     75 2.17.0
      1 2.17.GIT
     99 2.16.3.windows.1
     82 2.16.3
     68 2.16.2.windows.1
    112 2.16.2
     24 2.16.1.windows.4
      2 2.16.1.windows.3
      1 2.16.1.windows.2
     64 2.16.1.windows.1
     55 2.16.1
      7 2.16.0.windows.2
      1 2.16.0
      2 2.15.2
     60 2.15.1.windows.2
      2 2.15.1.windows.1
    305 2.15.1 (Apple Git-101)
     65 2.15.1
     60 2.15.0.windows.1
     81 2.15.0
      9 2.14.3.windows.1
     68 2.14.3 (Apple Git-98)
      7 2.14.3
     11 2.14.2.windows.3
      7 2.14.2.windows.2
      8 2.14.2.windows.1
     10 2.14.2
    105 2.14.1.windows.1
     36 2.14.1
      8 2.14.0.windows.2
      3 2.14.0.windows.1
      3 2.14.0
      6 2.13.6 (Apple Git-96)
      2 2.13.6
      2 2.13.5 (Apple Git-94)
      4 2.13.5
     35 2.13.3.windows.1
      7 2.13.3
     22 2.13.2.windows.1
     11 2.13.1.windows.2
      3 2.13.1.windows.1
      1 2.13.1.2143.gb1f2c4b
     17 2.13.1
     41 2.13.0.windows.1
     10 2.13.0
    330 2.12.3
     31 2.12.2.windows.2
      6 2.12.2.windows.1
      1 2.12.2 (Microsoft Windows NT 10.0.16299.0; Win
      1 2.12.2 (Microsoft Windows NT 10.0.15063.0; Win
      1 2.12.2 (Microsoft Windows NT 10.0.14393.0; Win
      4 2.12.2
      2 2.12.1.windows.1
     17 2.12.0.windows.1
     46 2.12.0
      3 2.11.3
     10 2.11.1.windows.1
     23 2.11.1
     20 2.11.0.windows.3
     21 2.11.0.windows.1
      9 2.11.0 (Apple Git-81)
     70 2.11.0
      1 2.11.GIT
     23 2.10.2.windows.1
      2 2.10.2
     24 2.10.1.windows.1
      3 2.10.1 (Apple Git-78)
     91 2.10.1
     16 2.10.0.windows.1
     24 2.10.0
      1 2.9.5
      1 2.9.3.windows.3
      1 2.9.3.windows.2
      3 2.9.3.windows.1
      1 2.9.3 (Apple Git-75)
     11 2.9.2.windows.1
      2 2.9.2 (Apple Git-74)
      9 2.9.2
      2 2.9.1
   1802 2.9.0.windows.1
      2 2.9.0
      2 2.8.6
      1 2.8.4.windows.1
      3 2.8.4 (Apple Git-73)
      1 2.8.3.windows.1
      1 2.8.3
      1 2.8.2.windows.1
     37 2.8.2
    566 2.8.1.windows.1
     41 2.8.1
      5 2.7.4.windows.1
      1 2.7.4 (Apple Git-66)
    431 2.7.4
      5 2.7.2.windows.1
      8 2.7.1
      1 2.7.0.windows.2
      3 2.7.0.windows.1
      1 2.6.4.windows.1
      1 2.6.4 (Apple Git-63)
      5 2.6.4
      4 2.6.3
      2 2.6.2.windows.1
      1 2.6.2
      3 2.6.1.windows.1
      1 2.6.0.windows.1
      1 2.5.4 (Apple Git-61)
      1 2.5.3.windows.1
      1 2.5.2
      1 2.5.0.windows.1
      1 2.5.0
      1 2.4.6.windows.1
      1 2.3.5
      1 2.3.2
      8 2.3.0
      7 2.2.1
     49 2.1.4
      1 2.1.0
      3 2.0.4
     12 2.0.1
      4 2.0.0
     17 2.0 (libgit2 0.27.0)
     84 2.0 (libgit2 0.26.0)
     20 1.9.5.msysgit.1
    119 1.9.5.msysgit.0
      2 1.9.4.msysgit.0
     47 1.9.4
      2 1.9.2.msysgit.0
      1 1.9.2
    152 1.9.1
      1 1.9.0.msysgit.0
      1 1.9.0
     85 1.8.5.6
      7 1.8.5.2
      4 1.8.4.2
      4 1.8.4
      5 1.8.3.msysgit.0
     92 1.8.3.1
      1 1.8.1.1
      2 1.8.1
   1650 1.7.12.4
      1 1.7.10.1
      3 1.7.9.5
      3 1.7.9.2
     36 1.7.3.4
     41 1.7.1
      1 1.0 (libgit2 0.26.0)
      1 1.0 (libgit2 0.25.1)
      1 1.0

**Comment by IngoS11** [comment]
I just created an issue in the abapGit Client. https://github.com/larshp/abapGit/issues/1432 maybe I can get them to adjust their versioning and be more like everyone else.

**Comment by larsxschneider** [comment]
Solved in https://github.com/larshp/abapGit/pull/1451 👍
