### ISSUE TITLE
Git-requests -> Operations

### ISSUE THREAD

**Issue by talktopiyush** [Autodesk/hubble#165]
I am looking for more description of this field Git-requests -> Operations? Any docs

Regards
Piyush

**Comment by talktopiyush** [comment]
not relevant. I found it myself

**Comment by pluehne** [comment]
@talktopiyush: I’m sorry that I didn’t come back to you about this. Actually, I’m not sure what you were referring to. Was this related to the dashboard or to code documentation? In either case, it makes sense to improve descriptions if they are incomplete :slightly_smiling_face:.
