### ISSUE TITLE
GHE - Hubble implementation, not able to view dashboard

### ISSUE THREAD

**Issue by gunjvm** [Autodesk/hubble#182]
Request your help for hubble.

I followed all the details mentioned on Hubble site https://github.com/Autodesk/hubble and implemented on our GHE Dev instance.

We can see the datafile created however the dashboard is empty, does not show any data 
https://fusiongithub.devfg.rbc.com/CM/hubble-data

Do you have idea or any known issues that i can follow

![hubble-dashboard](https://user-images.githubusercontent.com/7548862/58505782-bfb79f80-815b-11e9-872e-ed321e3cb702.PNG)
![huble-data](https://user-images.githubusercontent.com/7548862/58505792-c34b2680-815b-11e9-976e-b594c7fbd14e.PNG)

**Comment by pluehne** [comment]
Did you publish the `hubble-data` repository through GitHub Pages as explained in [step 2 of the *Getting Started* section](https://github.com/autodesk/hubble#getting-started)? If not, please do so. If `hubble-data` is correctly published, could you go to the Hubble dashboard with the web developer console open (Firefox or Chromium-based browsers)? In the *network* tab, you should see requests being made for `.tsv` files. Could you check what kind of error your browser reports for these `.tsv` files? See the following screenshot in case it’s not clear what I mean:

![web-console-network](https://user-images.githubusercontent.com/3244280/58511827-ec8ba700-819b-11e9-80bc-b61577603dcc.png)

**Comment by gunjvm** [comment]
Appreciate the quick reply.
Yes i did publish the page from master branch as mentioned in 2nd step. 

![image](https://user-images.githubusercontent.com/7548862/58527311-1fd03500-81a0-11e9-8ad1-6733cd4999bc.png)


however the published page shows blank data 
![image](https://user-images.githubusercontent.com/7548862/58527220-da136c80-819f-11e9-9887-e25a1b1089fc.png)

from the network tab it gives 404 page not found :(
![image](https://user-images.githubusercontent.com/7548862/58527283-0b8c3800-81a0-11e9-8449-9d084836d9de.png)

**Comment by gunjvm** [comment]
from logs - 

journalctl -fu hubble-enterprise.service
-- Logs begin at Mon 2018-07-09 17:19:52 UTC. --
May 29 03:52:28 fusiongithub-devfg-rbc-com python3[13078]: Started update of git-versions-new.tsv
May 29 03:52:28 fusiongithub-devfg-rbc-com python3[13078]: gzip: /var/log/haproxy.log.1*.gz: No such file or directory
May 29 03:52:28 fusiongithub-devfg-rbc-com python3[13078]: Finished update of git-versions-new.tsv (runtime: 0.018 s)
May 29 03:52:28 fusiongithub-devfg-rbc-com python3[13078]: Started update of organization-activity.tsv
May 29 03:52:28 fusiongithub-devfg-rbc-com sudo[13487]:    admin : TTY=unknown ; PWD=/opt/autodesk/hubble-enterprise ; USER=git ; COMMAND=/usr/local/bin/ghe-dbconsole -y
May 29 03:52:28 fusiongithub-devfg-rbc-com python3[13078]: mysql: [Warning] Using a password on the command line interface can be insecure.
May 29 03:52:28 fusiongithub-devfg-rbc-com python3[13078]: mysql: [Warning] Using a password on the command line interface can be insecure.
May 29 03:52:28 fusiongithub-devfg-rbc-com python3[13078]: Finished update of organization-activity.tsv (runtime: 0.825 s)
May 29 03:52:28 fusiongithub-devfg-rbc-com python3[13078]: Started update of org-collaboration.tsv
May 29 03:52:28 fusiongithub-devfg-rbc-com sudo[13525]:    admin : TTY=unknown ; PWD=/opt/autodesk/hubble-enterprise ; USER=git ; COMMAND=/usr/local/bin/ghe-dbconsole -y
May 29 03:52:29 fusiongithub-devfg-rbc-com python3[13078]: mysql: [Warning] Using a password on the command line interface can be insecure.
May 29 03:52:29 fusiongithub-devfg-rbc-com sudo[13665]:    admin : TTY=unknown ; PWD=/opt/autodesk/hubble-enterprise ; USER=git ; COMMAND=/usr/local/bin/ghe-dbconsole -y
May 29 03:52:30 fusiongithub-devfg-rbc-com python3[13078]: mysql: [Warning] Using a password on the command line interface can be insecure.
May 29 03:52:30 fusiongithub-devfg-rbc-com sudo[13765]:    admin : TTY=unknown ; PWD=/opt/autodesk/hubble-enterprise ; USER=git ; COMMAND=/usr/local/bin/ghe-dbconsole -y
May 29 03:52:31 fusiongithub-devfg-rbc-com python3[13078]: mysql: [Warning] Using a password on the command line interface can be insecure.
May 29 03:52:31 fusiongithub-devfg-rbc-com python3[13078]: mysql: [Warning] Using a password on the command line interface can be insecure.
May 29 03:52:31 fusiongithub-devfg-rbc-com python3[13078]: Finished update of org-collaboration.tsv (runtime: 2.681 s)
May 29 03:52:31 fusiongithub-devfg-rbc-com python3[13078]: Started update of org-owners.tsv
May 29 03:52:31 fusiongithub-devfg-rbc-com sudo[13861]:    admin : TTY=unknown ; PWD=/opt/autodesk/hubble-enterprise ; USER=git ; COMMAND=/bin/bash -c cd /data/github/current && . .app-config/production.sh && bin/runner -e production '
                                                                                        puts "organization        owner(s)
                                                        "
                                                                                        User.where(:type => "Organization")
                                                                                            .where("  login NOT LIKE \"github-enterprise\" ")
                                                                                            .order("login")
                                                                                            .each do |org|
                                                                                                owners = org.admins.where(:disabled => false, :suspended_at => nil, :gh_role => nil)
                                                                                                                   .where("")
                                                                                                                   .order("login")
                                                                                                                   .join(",")
                                                                                                puts "#{org.login}        #{owners}

**Comment by mzzmjd** [comment]
Did you follow step 5 with the correct URL:

> Open docs/_config.yml in your editor and set the dataURL that you noted earlier. Commit and push the change to your Hubble repository:
> git add docs/_config.yml
> git commit -m "Adjusting dataURL to our own instance"
> git push

So that your Hubble Dashboard points to your Hubble data pages site?

**Comment by gunjvm** [comment]
yes step 5 is also done as mentioned 
![image](https://user-images.githubusercontent.com/7548862/58577488-8ee77100-8214-11e9-837e-2835836ff10c.png)

![image](https://user-images.githubusercontent.com/7548862/58577589-cfdf8580-8214-11e9-9d4e-1fc6a24f452e.png)

**Comment by mzzmjd** [comment]
If you go to https://fusiongithub.devfg.rbc.com/stafftools/repositories/cm/hubble-data/pages does it show recent page builds and whether they are successful?

Can you also check https://fusiongithub.devfg.rbc.com/stafftools/repositories/cm/hubble/pages ?

**Comment by gunjvm** [comment]
how does it show recent page builds, not very much sure :( 
please find screenshote below - 

![stafftool-hubble-data](https://user-images.githubusercontent.com/7548862/58675819-00faab80-8324-11e9-8db2-ce242ab3a8cf.PNG)

![stafftool-hubble](https://user-images.githubusercontent.com/7548862/58675828-048e3280-8324-11e9-840d-e552496468a0.PNG)

**Comment by gunjvm** [comment]
Is it possible to schedule a screenshare wherein i can show my configuration if possible...

**Comment by mzzmjd** [comment]
Every time that a commit is made to the pages site repository (in particular hubble-data) it should trigger a build of the pages site.

Now obviously it has not built since 03 April 2019 (presumably when it was set up), so the data files are not shown on the hubble-data pages so hubble cannot pick up the data.

As a short term fix, can you click on the **Rebuild** button in both the pages at 
https://fusiongithub.devfg.rbc.com/stafftools/repositories/cm/hubble-data/pages
https://fusiongithub.devfg.rbc.com/stafftools/repositories/cm/hubble/pages

Be interesting to see if you get an error message.
https://help.github.com/en/enterprise/2.17/user/articles/troubleshooting-github-pages-builds

**Comment by gunjvm** [comment]
Hi team, as soon as i clicked on rebuild, it took a lot of time to load and now my dev instance went down :( 
Its giving the angry unicorn icon! 
I rebooted the vm too, it took half hour to restart, however still same unicorn. 
In backend we see error no memory left to allocate

**Comment by pluehne** [comment]
@gunjvm: Sounds like your GitHub Enterprise development instance doesn’t have enough resources allocated to it. You may need to assign more resources to it in order to have GitHub running along with all the services (such as GitHub Pages). In case this doesn’t help, I would contact GitHub Enterprise support to find out what’s going on. GitHub Pages is a standard GitHub service that should run without problems regardless of whether or not Hubble is installed.

**Comment by larsxschneider** [comment]
@pluehne your assumption was correct. An hardware upgrade fixed the issue.

**Comment by gunjvm** [comment]
Thanks a lot everyone, my issue is resolved. 
We upgraded the github dev instance to v2.17 and it required more memory as compared to 2.15 and hence it crashed. 
After the memory uplift and hubble re-initiation it works fine now.
