### ISSUE TITLE
Display "Loading" label in collaboration chart

### ISSUE THREAD

**Issue by larsxschneider** [Autodesk/hubble#20]
The "Collaboration Across Organizations" chart takes a bit of time on the first load if many organizations are visualized. A "Loading..." label would be nice to inform the user that things are happening.

**Comment by larsxschneider** [comment]
That sounds great! A generalized solution would be awesome! Loading the csv files takes a bit, too, from time to time! Please ping us if you're stuck at any point 👍

**Comment by filmaj** [comment]
I think we can close this now that #59 has been merged.
