### ISSUE TITLE
Feature request: Test suite/linter

### ISSUE THREAD

**Issue by filmaj** [Autodesk/hubble#58]
- `docs/assets/charts.js` is pretty big and as I look to contribute to the project, I would like to ensure I'm not breaking anything in there.
- adding a set of explicit JS linter rules for `charts.js` would be nice. I mentioned this for selfish reasons as my IDE currently looks like a red underline mess of spaghetti due to this project's preference for tabs 😜

**Comment by pluehne** [comment]
I totally agree we need a consistent coding style. @larsxschneider and I will discuss this tomorrow!

Aside from that, we’re definitely interested in having automated tests (especially for the updater, we didn’t think about testing the JavaScript side much yet). If you have suggestions about how best to test JavaScript functionality, we’d like to know about that 😃.

**Comment by filmaj** [comment]
>  If you have suggestions about how best to test JavaScript functionality, we’d like to know about that 😃.

Cool! I do have some suggestions on testing JavaScript, I love this topic 💃. I think all of it depends on how we want to be covered, how much code coverage we want, and how much tooling we're willing to have contributors require.

# How Much Tooling

We could leverage (and, implied here is: it will be required for developers / potential contributors) [node.js](http://nodejs.org), which gives us a JS runtime from the command-line. From there, we could formalize any config, dependencies and common project tasks (such as linting and testing) related to the web app / JS in a `package.json` file (a.k.a. node's `requirements.txt`). It'd be easy to formalize which test runner and linter we want to use - I'd suggest [jasmine](https://jasmine.github.io/) and [eslint](https://eslint.org) for those just because I have the most familiarity with them, but there are many to choose from and as long as this project picks one, that's what I care about most :). We can also encapsulate the test running and linting commands by defining "scripts" inside `package.json`. I recently worked on adding something similar to a JS project at Adobe - you can check out [the `package.json` for that](https://github.com/adobe/jsonschema2md/blob/master/package.json) for a sense of what I'm talking about. In particular the [`devDependencies` section](https://github.com/adobe/jsonschema2md/blob/master/package.json#L28) (which defines what dev tools we need like test runners and linters) as well as the [`scripts` section](https://github.com/adobe/jsonschema2md/blob/master/package.json#L9) (which defines what [commands we can run](https://github.com/adobe/jsonschema2md#tests)). With this setup, a potential contributor could clone the repo, and as long as they have node.js installed, could theoretically:

    $ cd docs
    $ npm install # use `npm` which comes with node.js to install any dependencies
    $ npm test # runs the tests, exits 0 when passing, 1 when fails
    $ npm run lint # verifies all JS in the project conforms to our defined style

If that seems too heavy (granted, this project already requires a Python runtime, so I can see that), we could go the simpler route of running tests inside the browser. The test runner I mentioned, Jasmine, runs just in the browser as well as node. With this method, we could add an additional `docs/tests/index.html` file that includes the Jasmine library, the JS files we want to test, e.g. `charts.js`, and `.js` file containing our tests. Potential contributors would need to manually open this `tests/index.html` up in their browser to figure out if tests pass or not. Going this approach would also likely need us to specify in more detail how to do all this, as it is a bit more manual and requires more human interaction. We'd also have to describe how to install a JS linter and how to run it from the command line.

# What Kind of Coverage

This one boils down to 'what sorts of tests do we think we need?' Unit tests are pretty standard and are a good starting point. If we end up hitting weird edge cases, like things not rendering properly in certain browsers or platforms, we may want to consider adding end-to-end tests using something like Selenium. My suggestion would be to stick to unit tests to start, and keep Selenium in our back pocket if we need it later.

# Looking Towards CI

One thing I would like for us to keep in mind for these decisions is that the next step I'd like to see for the project (and I'm more than happy to help with!) is to integrate this into a CI system, so we can get fast feedback on incoming changes (e.g. on PRs). We could leverage e.g. travis-ci.org for free for this. With this in mind, if we go the lighter run-inside-the-browser-kinda-manually method, I think that may be more difficult to automate. If we go with full-on node.js requirement, it'd be pretty easy to fully automate.

**Comment by larsxschneider** [comment]
Great write-up! I would love to see `node.js + recommended JS testrunner/linter + Travis CI` land in Hubble 👍 ! A test framework should have been in there from the start but we had to rush things a bit to get Hubble out of the door for GitHub Universe 😄 

If we have TravisCI running then we will for sure add a Python test framework, too.

---

PS: In the jsonschema2md project you linked I saw commits by @trieloff! I think he went to the same school as @pluehne and I ([HPI](https://hpi.de/en/)). Small world 😊 !

**Comment by filmaj** [comment]
Wow, small world indeed! 👋 @trieloff

Cool, I will take a stab at going the node.js route and send a PR for that for review. I think I will break the work up into two phases:

1. Add some JS tests, test runner, linter, run tasks and docs on how to run the tests for the web app / JS portion of Hubble.
2. Once that lands / is acceptable, we can talk about and make progress on running all of that in Travis and reporting feedback to PRs - with an eye toward also supporting running Python tests in the future (I found a [good StackOverflow question covering the topic of running tests in multiple runtimes](https://stackoverflow.com/questions/27644586/how-to-set-up-travis-ci-with-multiple-languages) that I will use as inspiration, I think).

**Comment by filmaj** [comment]
Relevant PR in 👉  #61
