### ISSUE TITLE
No more mouse over?

### ISSUE THREAD

**Issue by toddocon** [Autodesk/hubble#62]
I just updated to the latest Hubble and now I no longer have mouse over information like mousing over bubbles or the bands in the collaboration charts.

I also reloaded the site in Safari in a new private window, I see the same behavior.

**Comment by toddocon** [comment]
And links is also broken. This would include Organization names and ORG/repo in API requests, etc...

We had only changed 3 files locally for site specific settings. There was one conflict for docs/_config.yml (the URL of course). All other changes merged fine.

**Comment by pluehne** [comment]
I can reproduce this on http://autodesk.github.io/hubble/.

**Comment by filmaj** [comment]
I think this is related to the spinner I added (#59) - the container element housing the spinner stays on top of the graph, preventing any mouse over interactions.

I'll have a PR w/ a fix shortly.

**Comment by pluehne** [comment]
@filmaj: No worries, and thanks for taking care of this 👍!

**Comment by filmaj** [comment]
Fix for this is available in #63

**Comment by larsxschneider** [comment]
@toddocon: @filmaj fixed it! Can you check on your end?

**Comment by toddocon** [comment]
Just merged with latest Hubble. Confirmed, this is fixed now. Thank you all.

**Comment by filmaj** [comment]
😅
