### ISSUE TITLE
Updater service not triggered without user session

### ISSUE THREAD

**Issue by mzzmjd** [Autodesk/hubble#71]
When using the hubble-enterprise.timer on the appliance server, statistics are never collated. It seems that when you log off the primary server the updater stops too.

```[ghebackup@ghebackup ~]$ ssh -p 122 admin@github
     ___ _ _   _  _      _      ___     _                    _
    / __(_) |_| || |_  _| |__  | __|_ _| |_ ___ _ _ _ __ _ _(_)___ ___
   | (_ | |  _| __ | || | '_ \ | _|| ' \  _/ -_) '_| '_ \ '_| (_-</ -_)
    \___|_|\__|_||_|\_,_|_.__/ |___|_||_\__\___|_| | .__/_| |_/__/\___|
                                                   |_|

Administrative shell access is permitted for troubleshooting and performing
documented operations procedures only. Modifying system and application files,
running programs, or installing unsupported software packages may void your
support contract. Please contact GitHub Enterprise technical support at
enterprise@github.com if you have a question about the activities allowed by
your support contract.
Last login: Thu Dec 21 07:11:59 2017 from [masked-ip-address]
admin@github-primary:~$ journalctl -f --user-unit hubble-enterprise.timer
-- Logs begin at Wed 2017-06-21 20:01:19 UTC. --
Dec 21 06:59:43 github-primary systemd[23519]: Starting Runs Hubble Enterprise updater periodically.
Dec 21 06:59:43 github-primary systemd[23519]: Started Runs Hubble Enterprise updater periodically.
Dec 21 07:11:56 github-primary systemd[23519]: Stopping Runs Hubble Enterprise updater periodically.
Dec 21 07:11:56 github-primary systemd[23519]: Stopped Runs Hubble Enterprise updater periodically.
Dec 21 07:11:59 github-primary systemd[16682]: Starting Runs Hubble Enterprise updater periodically.
Dec 21 07:11:59 github-primary systemd[16682]: Started Runs Hubble Enterprise updater periodically.
Dec 21 07:13:16 github-primary systemd[16682]: Stopping Runs Hubble Enterprise updater periodically.
Dec 21 07:13:16 github-primary systemd[16682]: Stopped Runs Hubble Enterprise updater periodically.
Dec 21 07:16:13 github-primary systemd[22010]: Starting Runs Hubble Enterprise updater periodically.
Dec 21 07:16:13 github-primary systemd[22010]: Started Runs Hubble Enterprise updater periodically.
```
From the above, I logged in and 07:11:59 and logged out at 07:13:16. Then logged back in at 07:16:13.
Seems that you have to remain logged in for the collator to work.

The service collator works fine, but it has to be run manually every day.

Currently running on GHE Version 2.11.4 (but it also did this on GHE Version 2.10)
Using hubble-enterprise_0.1.1_all.deb

**Comment by mlbright** [comment]
Did you run:
```
systemctl --user enable hubble-enterprise.timer
```
?
If so, I wonder if [this](https://wiki.archlinux.org/index.php/Systemd/User#Automatic_start-up_of_systemd_user_instances) is the issue. @pluehne Is this necessary:
```
sudo loginctl --no-ask-password enable-linger admin
```

**Comment by mzzmjd** [comment]
Yes ran:
```
systemctl --user enable hubble-enterprise.timer
systemctl --user start hubble-enterprise.timer
```
As per instructions on [README.md](https://github.com/Autodesk/hubble/blob/master/updater/README.md)

**Comment by larsxschneider** [comment]
@mzzmjd "The updater" has two parts. A `timer` that kicks of the update mechanism once a day and a `service` runs the actual update.

I am not sure what is wrong on your end, yet. Let's look at the debug output of the `service`:
```
journalctl -f --user-unit hubble-enterprise.service
```
What does this tell you?

**Comment by larsxschneider** [comment]
Plus, what does this tell you?
```
systemctl --user list-unit-files | grep hubble
```

**Comment by mzzmjd** [comment]
```journalctl -f --user-unit hubble-enterprise.service``` produces the output:
```
-- Logs begin at Wed 2017-06-21 20:01:19 UTC. --
Dec 21 07:06:15 github-primary python3[4635]: /tmp/hubble-data/contributors-by-repository.tsv
Dec 21 07:06:15 github-primary python3[4635]: /tmp/hubble-data/forks-to-organizations.tsv
Dec 21 07:06:15 github-primary python3[4635]: /tmp/hubble-data/git-download.tsv
Dec 21 07:06:15 github-primary python3[4635]: /tmp/hubble-data/git-requests.tsv
Dec 21 07:06:15 github-primary python3[4635]: /tmp/hubble-data/git-versions.tsv
Dec 21 07:06:15 github-primary python3[4635]: /tmp/hubble-data/org-collaboration.tsv
Dec 21 07:06:15 github-primary python3[4635]: /tmp/hubble-data/org-owners.tsv
Dec 21 07:06:15 github-primary python3[4635]: /tmp/hubble-data/orgs-total.tsv
Dec 21 07:06:15 github-primary python3[4635]: /tmp/hubble-data/pull-requests-by-organization.tsv
Dec 21 07:06:15 github-primary python3[4635]: /tmp/hubble-data/pull-requests-by-repository.tsv
```
(This is the last time that I ran it as enterprise.service.)

```systemctl --user list-unit-files | grep hubble``` returns:
```
hubble-enterprise.service static
hubble-enterprise.timer   enabled
```

```journalctl -f --user-unit hubble-enterprise.timer``` today shows:
```
-- Logs begin at Wed 2017-06-21 20:01:19 UTC. --
Dec 21 07:16:13 github-primary systemd[22010]: Starting Runs Hubble Enterprise updater periodically.
Dec 21 07:16:13 github-primary systemd[22010]: Started Runs Hubble Enterprise updater periodically.
Dec 21 07:29:28 github-primary systemd[22010]: Stopping Runs Hubble Enterprise updater periodically.
Dec 21 07:29:28 github-primary systemd[22010]: Stopped Runs Hubble Enterprise updater periodically.
Dec 21 11:18:00 github-primary systemd[24230]: Starting Runs Hubble Enterprise updater periodically.
Dec 21 11:18:00 github-primary systemd[24230]: Started Runs Hubble Enterprise updater periodically.
Dec 21 14:42:47 github-primary systemd[24230]: Stopping Runs Hubble Enterprise updater periodically.
Dec 21 14:42:47 github-primary systemd[24230]: Stopped Runs Hubble Enterprise updater periodically.
Dec 22 07:04:48 github-primary systemd[3921]: Starting Runs Hubble Enterprise updater periodically.
Dec 22 07:04:48 github-primary systemd[3921]: Started Runs Hubble Enterprise updater periodically.
```
(Again these coincide with login / logout to primary server).

**Comment by larsxschneider** [comment]
Do you recall any modifications to your GHE instance? The timer should kick off the process [*once a day* at 7:30AM UTC](https://github.com/Autodesk/hubble/blob/master/updater/systemd/hubble-enterprise.timer).

Just to double check: You did not see any updates after you let it sit for two days?

One more thing: if you run the process *manually* for a given day, then the *automatic* process won't do anything (because we only want to have one data item per day). Can you clone your `hubble-data` repo, run `git log`, and post the result?

**Comment by mzzmjd** [comment]
The timer has never run. I have left it every day since installing on 09 October 2017.

I am not sure whether I have ever been logged in as admin at 07:30 UTC, so don't know whether that would start the compilation. I will try tomorrow by staying logged in.

This also happened on Version 2.10 as well as Version 2.11.

This is a vanilla version of GitHub Enterprise, no other changes have been made to the installation. This is a High Availability install with a single Replica server.

**Comment by larsxschneider** [comment]
Hmm... your log confirms the problem. Being "logged in" should not be necessary at all for the timer.
@pluehne do you have a clue?

@mlbright I would be surprised if we would need to set any additional setting as Hubble runs with the given settings on a number of GHE instances without issues.

**Comment by larsxschneider** [comment]
Hmm... maybe @mlbright is right after all.

@mzzmjd Can you login to your machine and start a `screen` session? Then kill the connection to keep the screen session open.

**Comment by mzzmjd** [comment]
That seems to have started the updater and it hasn't stopped. I will leave it running over night and check tomorrow morning and report back.

**Comment by mzzmjd** [comment]
By starting the ``` screen ``` session and then killing the connection, that seems to have worked. The statistics have collated automatically. :+1: 

Great stuff. 😃

**Comment by larsxschneider** [comment]
Thanks for the feedback 👍 

However, this is definitely a bug in our setup. A `screen` session should not be necessary. We will find a fix soon!

**Comment by pluehne** [comment]
@mzzmjd: We’ve already had some issues with `systemd`’s user services (for example, user services can’t depend on system services because of the current design of `systemd`). As user services turn out problematic once more, @larsxschneider and I decided to switch to a system service now, which would also resolve the issues you experienced.

I’m now making the necessary changes—stay tuned 😃. And sorry for the late response due to the Christmas break!
